package com.route.islamyapplication

import com.route.islamyapplication.models.SurahandAyat

object Constants {
    val SOBHANAALLA :String= "سبحان الله"
    val ELHAMDLLALLA :String= "الحمد لله"
    val ALLAHAKBER :String= "الله اكبر"
    val NAMEKEY="NAMEKEY"
    val NAMEOFFILEKEY = "FILEKEY"
    val NAMEOFHADETHKEY ="HADETH"
    val CONTENTOFHADETH = "CONTENT"

    val NAMESANDNUMBEROFAYAT =  mutableListOf<SurahandAyat>(
         SurahandAyat("الفاتحه",7)
        , SurahandAyat("البقرة",286)
        , SurahandAyat("آل عمران",200)
        , SurahandAyat("النساء",176)
        , SurahandAyat("المائدة",120)
        , SurahandAyat("الأنعام",165)
        , SurahandAyat("الأعراف",206)
        , SurahandAyat("الأنفال",75)
        , SurahandAyat("التوبة",129)
        , SurahandAyat("يونس",109)
        , SurahandAyat("هود",123)
        , SurahandAyat("يوسف",111)
        , SurahandAyat("الرعد",43)
        , SurahandAyat("إبراهيم",52)
        , SurahandAyat("الحجر",99)
        , SurahandAyat("النحل",128)
        , SurahandAyat("الإسراء",111)
        , SurahandAyat("الكهف",110)
        , SurahandAyat("مريم",98)
        , SurahandAyat("طه",135)
        , SurahandAyat("الأنبياء",112)
        , SurahandAyat("الحج",78)
        , SurahandAyat("المؤمنون",118)
        , SurahandAyat("النّور",64)
        , SurahandAyat("الفرقان",77)
        , SurahandAyat("الشعراء",227)
        , SurahandAyat("النّمل",93)
        , SurahandAyat("القصص",88)
        , SurahandAyat("العنكبوت",69)
        , SurahandAyat("الرّوم",60)
        , SurahandAyat("لقمان",34)
        , SurahandAyat("السجدة",30)
        , SurahandAyat("الأحزاب",73)
        , SurahandAyat("سبأ",54)
        , SurahandAyat("فاطر",45)
        , SurahandAyat("يس",83)
        , SurahandAyat("الصافات",182)
        , SurahandAyat("ص",88)
        , SurahandAyat("الزمر",75)
        , SurahandAyat("غافر",85)
        , SurahandAyat("فصّلت",54)
        , SurahandAyat("الشورى",53)
        , SurahandAyat("الزخرف",89)
        , SurahandAyat("الدّخان",59)
        , SurahandAyat("الجاثية",37)
        , SurahandAyat("الأحقاف",35)
        , SurahandAyat("محمد",38)
        , SurahandAyat("الفتح",29)
        , SurahandAyat("الحجرات",18)
        , SurahandAyat("ق",45)
        , SurahandAyat("الذاريات",60)
        , SurahandAyat("الطور",49)
        , SurahandAyat("النجم",62)
        , SurahandAyat("القمر",55)
        , SurahandAyat("الرحمن",78)
        , SurahandAyat("الواقعة",96)
        , SurahandAyat("الحديد",29)
        , SurahandAyat("المجادلة",22)
        , SurahandAyat("الحشر",24)
        , SurahandAyat("الممتحنة",13)
        , SurahandAyat("الصف",14)
        , SurahandAyat("الجمعة",11)
        , SurahandAyat("المنافقون",11)
        , SurahandAyat("التغابن",18)
        , SurahandAyat("الطلاق",12)
        , SurahandAyat("التحريم",12)
        , SurahandAyat("الملك",30)
        , SurahandAyat("القلم",52)
        , SurahandAyat("الحاقة",52)
        , SurahandAyat("المعارج",44)
        , SurahandAyat("نوح",28)
        , SurahandAyat("الجن",28)
        , SurahandAyat("المزّمّل",20)
        , SurahandAyat("المدّثر",56)
        , SurahandAyat("القيامة",40)
        , SurahandAyat("الإنسان",31)
        , SurahandAyat("المرسلات",50)
        , SurahandAyat("النبأ",40)
        , SurahandAyat("النازعات",46)
        , SurahandAyat("عبس",42)
        , SurahandAyat("التكوير",29)
        , SurahandAyat("الإنفطار",19)
        , SurahandAyat("المطفّفين",36)
        , SurahandAyat("الإنشقاق",25)
        , SurahandAyat("البروج",22)
        , SurahandAyat("الطارق",17)
        , SurahandAyat("الأعلى",19)
        , SurahandAyat("الغاشية",26)
        , SurahandAyat("الفجر",30)
        , SurahandAyat("البلد",20)
        , SurahandAyat("الشمس",15)
        , SurahandAyat("الليل",21)
        , SurahandAyat("الضحى",11)
        , SurahandAyat("الشرح",8)
        , SurahandAyat("التين",8)
        , SurahandAyat("العلق",19)
        , SurahandAyat("القدر",5)
        , SurahandAyat("البينة",8)
        , SurahandAyat("الزلزلة",8)
        , SurahandAyat("العاديات",11)
        , SurahandAyat("القارعة",11)
        , SurahandAyat("التكاثر",8)
        , SurahandAyat("العصر",3)
        , SurahandAyat("الهمزة",9)
        , SurahandAyat("الفيل",5)
        , SurahandAyat("قريش",4)
        , SurahandAyat("الماعون",7)
        , SurahandAyat("الكوثر",3)
        , SurahandAyat("الكافرون",6)
        , SurahandAyat("النصر",3)
        , SurahandAyat("المسد",5)
        , SurahandAyat("الإخلاص",4)
        , SurahandAyat("الفلق",5)
        , SurahandAyat("الناس",6)




    )
}